Repository mobi-projects/catch-poket-mon, pull requests merged in 2024-05, with the labels that each got.

#25 PR: design/Header 완료했습니다.
  src/assets/imgs/monsterball.png
  src/components/layouts/header.tsx
  src/libs/tailwindCss/designToken/color.ts
  src/libs/tailwindCss/designToken/fontSize.ts
Labels: design, 0순위

#26 PR: design/Footer
  src/components/layouts/footer.tsx
Labels: design, 0순위

#27 PR : Design/signup page
  src/assets/imgs/signupImg-removebg-preview.png
  src/libs/router/router.tsx
  src/pages/signinPage.tsx
  src/pages/signupPage.tsx
Labels: design, 0순위

#28 PR : Design/my page
  package-lock.json
  package.json
  src/libs/router/adminRouter.tsx
  src/libs/router/router.tsx
  src/libs/tailwindCss/designToken/color.ts
  src/pages/myInfoPage.tsx
Labels: design, 0순위

#30 PR : feat/overlay 생성
  src/components/commons/overlay.tsx
Labels: feat, 1순위

#31 PR : design/pokemonDetailPage
  src/components/pokemonDetailPage/pokeEvolution.tsx
  src/components/pokemonDetailPage/pokeInfo.tsx
  src/libs/router/adminRouter.tsx
  src/pages/poketMonDetailPage.tsx
  src/pages/signupPage.tsx
Labels: design, 나중에

#32 PR : feat/loadingPage
  src/assets/imgs/ball.png
  src/components/loadingPage.tsx
  tailwind.config.js
Labels: feat, 1순위

#33 Pr: Design/main page
  src/App.tsx
  src/assets/imgs/examplePoke.png
  src/assets/imgs/unknown.png
  src/components/main/encounterPoke.tsx
  src/components/main/mainBackground.tsx
  src/components/main/startPoke.tsx
  src/libs/redux/gameStartSlice.ts
  src/libs/redux/store.ts
  src/pages/mainPage.tsx
  tailwind.config.js
Labels: 1순위

#37 PR: feat/userApi 생성완료
  src/libs/axios/axiosInstance.ts
  src/libs/axios/userAPI.ts
Labels: feat, 1순위

#41 PR : feat/main page
  .gitignore
  src/components/main/encounterPoke.tsx
  src/hook/usePokeData.ts
  src/hook/useRandomPokeData.ts
  src/libs/axios/dataAPI.ts
  src/libs/axios/pokeAPI.ts
  src/libs/axios/userAPI.ts
  src/types/pokeTypes/pokemonType.ts
  src/types/pokeTypes/speciesType.ts
  src/utils/storageUtils.ts
Labels: feat, 2순위

#42 PR: feat/common-button 생성했습니다
  src/components/commons/button.tsx
Labels: feat, 1순위

#43 PR : feat/common-input
  src/components/commons/input.tsx
Labels: feat, 1순위

#45 PR : feat/common modal
  src/components/commons/modal.tsx
  src/components/commons/overlay.tsx
Labels: feat, 1순위

#46 PR: Feat/signin page
  package-lock.json
  package.json
  src/components/commons/input.tsx
  src/constants/schema.ts
  src/hook/useLogin.ts
  src/pages/signinPage.tsx
Labels: feat, 2순위

#47 PR : refactor/main page
  src/components/commons/modal.tsx
  src/components/main/encounterPoke.tsx
  src/components/main/encounterPokeScreen.tsx
  src/components/main/successFailOverlay.tsx
  src/hook/useCatchPokemon.ts
  src/hook/useRandomPokeData.ts
  src/libs/axios/axiosInstance.ts
  src/libs/axios/dataAPI.ts
  src/types/pokeTypes/abilityType.ts
  src/types/pokeTypes/pokemonType.ts
  src/types/pokeTypes/speciesType.ts
  src/utils/encounterPokeUtils.ts
  tsconfig.json
Labels: feat, 2순위

#48 PR: Feat/signup page
  src/components/commons/input.tsx
  src/components/signin/signinForm.tsx
  src/components/signin/signinScreen.tsx
  src/components/signup/signupForm.tsx
  src/constants/schema.ts
  src/hook/useSignin.ts
  src/hook/useSignup.ts
  src/pages/signinPage.tsx
  src/pages/signupPage.tsx
Labels: feat, 2순위

#50 PR:feat/common-typeButton
  src/components/commons/typeButton.tsx
Labels: feat, 2순위

#54 PR: refactor/sign 오타 수정 및 불필요한 로직 삭제 및 modal 추가
  src/components/signin/signinForm.tsx
  src/components/signup/signupForm.tsx
  src/constants/schema.ts
  src/hook/useSignin.ts
  src/hook/useSignup.ts
  src/libs/axios/userAPI.ts
Labels: chore

#56 PR : refactor/pokebasket
  src/components/myinfo/logoutButton.tsx
  src/components/myinfo/userInfo.tsx
  src/libs/axios/userAPI.ts
  src/pages/myInfoPage.tsx
Labels: chore

#58 PR : refactor/pokeApi 포켓몬 종류 추가 250->600마리
  src/hook/useRandomPokeData.ts
  src/libs/axios/pokeAPI.ts
Labels: chore

#62 PR : refactor 포획 하기 중복 클릭 방지 로직 추가
  src/components/main/encounterPokeScreen.tsx
  src/components/main/successFailOverlay.tsx
  src/libs/redux/catchingSlice.ts
  src/libs/redux/store.ts
Labels: chore

#65 PR: refactor / pokemonDetailPage 수정
  src/components/myinfo/pokemonBasket.tsx
  src/components/pokemonDetailPage/pokeInfo.tsx
  src/libs/tailwindCss/designToken/color.ts
  src/pages/poketMonDetailPage.tsx
Labels: chore

#66 PR: fix/ pokeDetailPage error수정
  src/libs/router/router.tsx
  src/pages/poketMonDetailPage.tsx
Labels: fix, 0순위

#68 PR : feat/drop poke
  src/components/commons/modal.tsx
  src/components/myinfo/pokeReleaseButton.tsx
  src/components/myinfo/pokemonBasket.tsx
  src/libs/axios/dataAPI.ts
  src/types/pokeTypes/pokemonData.ts
Labels: feat, 2순위

#69 PR : feat/user info1-1
  src/components/commons/input.tsx
  src/components/myinfo/logoutButton.tsx
  src/components/myinfo/userInfo.tsx
  src/components/signup/signupForm.tsx
  src/constants/schema.ts
  src/hook/useSignup.ts
  src/libs/axios/dataAPI.ts
  src/libs/axios/userAPI.ts
Labels: chore, feat, 2순위

#70 PR : refactor/signin page button 추가
  src/components/signin/signinScreen.tsx
Labels: chore

#71 PR: feat/user profile1-1
  src/components/myinfo/pokemonBasket.tsx
  src/components/myinfo/profileChange.tsx
  src/components/myinfo/userInfo.tsx
  src/hook/useProfileUpdate.ts
  src/hook/useSignin.ts
  src/libs/axios/userAPI.ts
  src/pages/myInfoPage.tsx
  src/utils/storageUtils.ts
Labels: feat, 2순위

#73 PR : refactor/design 반응형 설정
  src/components/layouts/header.tsx
  src/components/main/encounterPokeScreen.tsx
  src/components/main/mainBackground.tsx
  src/components/main/startPoke.tsx
Labels: design

#74 PR: refactor/nick name update 로직 분리
  src/components/myinfo/userInfo.tsx
  src/hook/useUpdateUser.ts
Labels: chore
